spring.application.name=calibre-api
spring.datasource.url=jdbc:sqlite:file:metadata.db?date_class=TEXT&date_format=yyyy-MM-dd HH:mm:ss.SSSSSSXXX
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=com.example.calibreapi.config.CustomSQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.root=info
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG
